### PR TITLE
Cleanup and ember

### PR DESCRIPTION
**Pull request by fsmanuel**

### CODE REVIEW

**Comment by steveklabnik** [comment]
This is so awesome. I was literally sitting down to write this code when the PR came in! :heart: 

If this were a bigger project, I might ask you to clean up the commits a bit, but since this isn't anything serious, I don't mind. Thank you so much!!!!

**Comment by fsmanuel** [comment]
Will rebase in the future.

**Comment by steveklabnik** [comment]
Do you plan on contributing more in the future? maybe we should chat about things we can add :)

My primary goal is to create pages like "Most depended on crates" and such.

**Comment by fsmanuel** [comment]
@steveklabnik if time permits I'll contribute. Rust is still very new to me so i consider to contribute more on the ember side.
I like the idea to highlight crates that are important to the ecosystem. What I find useful in emberland is emberobserver.com to get a feeling what packages are "good quality" and the categories to find alternatives.

**Pull request merged**
